### PR TITLE
Fixed bug in list function, only showing the firsts 100 files

### PR DESCRIPTION
**Pull request by sebastian-greco**
Per documentation, when asking for files using the readEntries method:
" Call this method until an empty array is returned." the previous code was calling that only once.
https://developer.mozilla.org/it/docs/Web/API/DirectoryReader#readEntries

### CODE REVIEW

**Comment by markmarijnissen** [comment]
You've made the changes in the `dist` directory which will get overwritten when you build the project. Can you make the same modification on the main source file? index.js?

**Comment by sebastian-greco** [comment]
Sure, sorry about that, I was in a hurry with a project when I did that change. Let me change that

**Comment by sebastian-greco** [comment]
Updated

**Comment by domharrington** [comment]
This pull request broke the unit tests. In master:

screen shot 2016-05-04 at 17 43 13

Then if i checkout the commit before this one 65324a61c583816ba38a463a002aecf26452310d all list related tests pass:

screen shot 2016-05-04 at 17 45 54

**Pull request merged**
